# Numpy数组的优势
Numpy数组通常是由相同种类的元素组成的，即数组中的数据项的类型必须一致

In [1]:
import numpy as np

# range()与np.arange()的使用

###### range()返回的是range object,而np.arange()返回的是numpy.ndarray()
###### np.arange()支持步长为小数
###### 两者都有第三个参数，以第一个参数为起点，第三个参数为步长，截止到第二个参数

In [6]:
a=np.arange(5)
a.dtype

dtype('int32')

In [7]:
a

array([0, 1, 2, 3, 4])

In [8]:
a.shape

(5,)

如你所见，该向量有5个元素，他们的分别是从0到4，该数组的shape属性是一个元祖，存放的是数组在每一个维度的长度。

# 创建多维数组

In [10]:
m=np.array([np.arange(2),np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [11]:
m.shape

(2, 2)

# 选择Numpy数组元素
 有时，我们可能想从数组中选择指定的元素。如何做到这一点呢？不放葱穿件一个2行2列的矩阵着手

In [15]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

上面的矩阵是通过向array()函数传递一个由列表组成的列表得到的，接下来，我们要逐个选择矩阵的各个元素，代码如下所示。别忘了，下标是从0开始的

In [14]:
a[0,0]

1

## 许多函数都带有一个指定数据类型的参数，该参数通常是可选的:

In [17]:
np.arange(7,dtype=float)

array([0., 1., 2., 3., 4., 5., 6.])

# 一维数组的切片与索引
 一维numpy数组的切片操作与python列表的切片一样。下面先来定义包括0,1,2，直到8的一个数组，然后通过指定下标3与7来选择该数组的部分元素，实际上就是提取数组中值为3到6的那些元素

In [18]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
a[3:7]

array([3, 4, 5, 6])

In [20]:
a[:7:2]

array([0, 2, 4, 6])

In [21]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

# 使用ravel()、flatten()、shape()、resize()数组形态变化
前面，我们已经学过了reshape(),实际上，除了数组形状调整外，数组的扩充也是一个经常碰到的乏味工作。比如，可以想象一下将多维数组转换成一维数组时的情形。

In [30]:
print('In:b=np.arange(24).reshape(2,3,4)')
b=np.arange(24).reshape(2,3,4)
print('In:b')
print(b)

In:b=np.arange(24).reshape(2,3,4)
In:b
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [33]:
b.ravel()         #把数组变成一维数组 但只返回数组视图

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
b.flatten()       #同样是把数组变为一维 返回真实数组占内存

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [28]:
b.shape=(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
b.resize(2,12)       #类似reshape() 但是会改变所作用的数组
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

# 数组叠加
数组既可以横向叠放，也可以竖向叠放，为此，可以使用vstack()、stack()、hstack()、column_stack()、row_stack()、concatenate()等函数。

In [37]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
b=2*a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

## 水平叠加np.hstack()
先介绍水平叠加方式，即用元组确定ndarrays数组的形状，然后交由hastack()函数来码放这些数组

In [47]:
np.hstack([a,b])

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

## 垂直叠加:np.vstack()
使用垂直叠加方法时，先要构建一个元组，然后将元组交给vstack()函数来码放数组

In [48]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

## concatenate() 函数也能达到相同的效果。
axis=0垂直叠加，axis=1水平叠加

In [45]:
np.concatenate([a,b],axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [46]:
import pandas as pd
a=pd.DataFrame(a)
b=pd.DataFrame(b)
pd.concat((a,b),axis=0)

0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
0   0   2   4
1   6   8  10
2  12  14  16

## 深度叠加np.dstack()
除此之外，还有一种深度叠加方法，这要用到dstack()函数和一个元组。这种方法是沿着第三个坐标轴（纵向）的方法叠加一组数组。举例来说，可以在一个图像数据的二维数组上叠加另一幅图像的数据。

In [49]:
np.dstack((a,b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

## 列式堆叠np.column_stack() np.hstack() np.vstack（）
column_stack()函数以列方式对一维数组进行堆叠。

In [50]:
one=np.arange(2)
one

array([0, 1])

In [51]:
two=2*one
two

array([0, 2])

In [54]:
np.column_stack((one,two))

array([[0, 0],
       [1, 2]])

In [55]:
np.hstack((one,two))

array([0, 1, 0, 2])

In [63]:
np.vstack((one,two))

array([[0, 1],
       [0, 2]])